### ISSUE TITLE
rosie go: bad error message if [rosie-id] not defined

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#1634]
A user is getting this traceback on launching `rosie go`. I can reproduce this if a `[rosie-id]` section is not defined in the site/user configuration. We could do with a better error message.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/rose-2015.05.0/lib/python/rosie/browser/main.py", line 1457, in <module>
    main()
  File "/opt/rose-2015.05.0/lib/python/rosie/browser/main.py", line 1439, in main
    raise exc
AttributeError: 'NoneType' object has no attribute 'get_value'
```

**Comment by solenostomus** [comment]
I got the error just after installing rose before doing any configuration, so the file $ROSE_HOME/etc/rose.conf did not yet exist.
So I would have preferred an error message that points me towards the creation of this file.

If the file exists then it should warn that the [rosie-id] section is missing.
