### ISSUE TITLE
rose edit: fix um stash widget 'remove all' package

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1774]
The 'Remove all' and 'Ignore all' package menu options in rose edit's UM STASH widget do not work.

**Comment by arjclark** [comment]
"Disable all" also doesn't work. Failing with traceback:
```
Traceback (most recent call last):
  File ".../rose.git/lib/python/rose/config_editor/plugin/um/widget/stash.py", line 822, in <lambda>
    lambda i: self._packages_enable(disable=True))
  File ".../rose.git/lib/python/rose/config_editor/plugin/um/widget/stash.py", line 875, in _packages_enable
    self.sub_ops.ignore_sections(sections_for_changing, disable)
  File ".../rose.git/lib/python/rose/config_editor/ops/group.py", line 435, in ignore_sections
    is_ignored)
  File ".../rose.git/lib/python/rose/config_editor/ops/group.py", line 345, in ignore_sections
    self.sect_ops.trigger_update(ns, skip_sub_data_update=True)
  File ".../rose.git/lib/python/rose/config_editor/main.py", line 1087, in update_namespace
    self.updater.update_namespace(*args, **kwargs)
  File ".../rose.git/lib/python/rose/config_editor/updater.py", line 211, in update_namespace
    self.update_sections(namespace)
  File ".../rose.git/lib/python/rose/config_editor/updater.py", line 290, in update_sections
    config_name = self.util.split_full_ns(self.data, namespace)[0]
  File ".../rose.git/lib/python/rose/config_editor/util.py", line 79, in split_full_ns
    if full_namespace not in self.full_ns_split_lookup:
TypeError: unhashable type: 'list'
```
