### ISSUE TITLE
rose edit: crashes when Launch Suite Control GUI clicked and suite is not running

### ISSUE THREAD

**Issue by RosalynHatcher** [metomi/rose#1910]
When the "Launch Suite Control GUI" button is clicked in `rose edit` for a suite that is currently not running `rose edit` crashes with the following error:

    Traceback (most recent call last):
      File "/home/fcm/rose-2016.05.1/lib/python/rose/gtk/util.py", line 294, in <lambda>
        lambda b: function())
      File "/home/fcm/rose-2016.05.1/lib/python/rose/config_editor/menu.py", line 946, in launch_scheduler
        return scontrol.gcontrol(this_id)
      File "/home/fcm/rose-2016.05.1/lib/python/rose/suite_control.py", line 88, in gcontrol
        raise SuiteNotRunningError(suite_name)
    rose.suite_control.SuiteNotRunningError: u-ad849: does not appear to be running

A few versions ago this didn't happen and the `gcylc` window would simply show as empty.

**Comment by arjclark** [comment]
@RosalynHatcher - good spot. We caught the same problem in rosie go (#1875) but hadn't noted it for rose edit. Will put up a fix shortly.

**Comment by oliver-sanders** [comment]
Closed by #1911
