### ISSUE TITLE
Rose Bush: `serve_fileobj` traceback

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/rose#1922]
`cherrypy.lib.static.serve_fileobj` does not exist on cherrypy versions < 3.2.
Our documentation states `3.1.2`, so one of these should change.

```
Traceback (most recent call last):
    File "/opt/rose/lib/python/rose/bush.py", line 608, in view
        user, suite, path, path_in_tar=path_in_tar, mode=mode)
    File "/opt/rose/lib/python/rose/bush.py", line 518, in get_file return
        cherrypy.lib.static.serve_fileobj(f, MIME_TEXT_PLAIN)
AttributeError: 'module' object has no attribute 'serve_fileobj' 
```

**Comment by matthewrmshin** [comment]
@oliver-sanders do you mind having a go at fixing this? (I think we are stuck at this version of cherrypy for a bit.)

**Comment by oliver-sanders** [comment]
@matthewrmshin On it.
