### ISSUE TITLE
rose edit: Showing variable info broken in trunk

### ISSUE THREAD

**Issue by MartinDix** [metomi/rose#1969]
In the trunk version of rose edit, clicking the gear icon beside a variable and selecting info gives a crash
```
Traceback (most recent call last):
  File ".../rose/lib/python/rose/config_editor/menuwidget.py", line 307, in _launch_info_dialog
    search_function)
  File ".../rose/lib/python/rose/config_editor/util.py", line 120, in launch_node_info_dialog
    att_list = vars(node).items()
TypeError: vars() argument must have __dict__ attribute
```
I think this is related to the introduction of slots in #1957. It seems with slots that objects no longer have a``` __dict__``` attribute.

**Comment by matthewrmshin** [comment]
@benfitzpatrick do you mind having a quick look at this?
