### ISSUE TITLE
rose edit: crash when searching for "vert", "vertical"

### ISSUE THREAD

**Issue by RosalynHatcher** [metomi/rose#1984]
Bit of a weird one....  
In rose edit, if you select the um app and then search for any of the following **ve**, **ver**, **vert**, **verti**, **vertic**, **vertica** or **vertical** rose edit crashes with the following error message:

```
Traceback (most recent call last):
  File "/home/fcm/rose-2016.07.0/lib/python/rose/gtk/util.py", line 294, in <lambda>
    lambda b: function())
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/main.py", line 1577, in _launch_find
    page, var_id = self.perform_find(expression, start_page)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/main.py", line 1608, in perform_find
    return self.view_page(page_id, var_id), var_id
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/main.py", line 1120, in view_page
    self.handle_launch_request(page_id, as_new=True)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/main.py", line 733, in handle_launch_request
    page = self.make_page(namespace_name)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/main.py", line 867, in make_page
    launch_macro_func=self.main_handle.handle_run_custom_macro
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/page.py", line 101, in __init__
    self.generate_main_container()
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/page.py", line 674, in generate_main_container
    self.show_modes)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/pagewidget/table.py", line 58, in __init__
    self.attach_variable_widgets(variable_is_ghost_list, start_index=0)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/pagewidget/table.py", line 109, in attach_variable_widgets
    variable_widget = self.get_variable_widget(variable, is_ghost)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/pagewidget/table.py", line 120, in get_variable_widget
    show_modes=self.show_modes)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/variable.py", line 72, in __init__
    self.generate_valuewidget(variable)
  File "/home/fcm/rose-2016.07.0/lib/python/rose/config_editor/variable.py", line 163, in generate_valuewidget
    arg_str=custom_arg)
TypeError: __init__() got an unexpected keyword argument 'arg_str'
```
This only appears to happen with the UM app as far as I can tell.
It occurs on both PUMA and MONSooN, but only seems to happen on MONSooN if you don't have anything selected in the Index pane (ie. on startup)

**Comment by arjclark** [comment]
@RosalynHatcher - this looks related the problem fixed by #1962. Could you test with rose 2016.09.0?

**Comment by RosalynHatcher** [comment]
@arjclark - thanks, missed that one.  I've tested with 2016.09.0 on MONSooN and that does indeed appear to have fixed it.  We've not yet got 2016.09.0 installed on PUMA but pretty sure it will be fine there too so happy for this to be closed.  If I do still find problems I'll reopen it.

**Comment by arjclark** [comment]
Cool, closing for now.
