### ISSUE TITLE
Splash Screen Recursion

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2148]
The way in which the rose splash screen is written creates the possibility of hitting the max recursion limit.

It would appear that past the splash screen itself such traceback otherwise is symptomless.

Such traceback is intermittent - to replicate add the following to the top of `lib/python/rose/gtk/splash.py`:

```python
sys.setrecursionlimit(1000)
```

Example stack from `rose edit` showing the recursive nature of calls:

```
  File ".../rose/lib/python/rose/gtk/splash.py", line 290, in _update_splash_screen
    *update_input["args"], **update_input["kwargs"])
  File ".../rose/lib/python/rose/gtk/splash.py", line 129, in update
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 148, in _pulse
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 290, in _update_splash_screen
    *update_input["args"], **update_input["kwargs"])
  File ".../rose/lib/python/rose/gtk/splash.py", line 129, in update
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 290, in _update_splash_screen
    *update_input["args"], **update_input["kwargs"])
  File ".../rose/lib/python/rose/gtk/splash.py", line 129, in update
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 290, in _update_splash_screen
    *update_input["args"], **update_input["kwargs"])
  File ".../rose/lib/python/rose/gtk/splash.py", line 129, in update
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 290, in _update_splash_screen
    *update_input["args"], **update_input["kwargs"])
  File ".../rose/lib/python/rose/gtk/splash.py", line 129, in update
    gtk.main_iteration()
  File ".../rose/lib/python/rose/gtk/splash.py", line 148, in _pulse
    gtk.main_iteration()
```

Reported by a user and seen before by myself.

A possible (dirty) bodge would be to increase the recursion limit.

**Comment by sadielbartholomew** [comment]
Another user has reported a variant of this problem, & I have also recreated it.

From our investigation it is not an *intermittent* problem, but a *suite-dependent* one. In particular, it seems to occur only for especially large suites (by suite & app variable number) such as the UM trunk.

In the cases noted, we see a variant of the traceback only referencing the main line, as above, upon start-up of offending suites:

```bash
Traceback (most recent call last):
  File "/net/home/h06/sbarth/rose.git/lib/python/rose/gtk/splash.py", line 129, in _start_pulse
    if (self._progress_message != idle_message or
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/net/home/h06/sbarth/rose.git/lib/python/rose/gtk/splash.py", line 129, in _start_pulse
    if (self._progress_message != idle_message or
RuntimeError: maximum recursion depth exceeded in cmp
Traceback (most recent call last):
  File "/net/home/h06/sbarth/rose.git/lib/python/rose/gtk/splash.py", line 287, in _update_splash_screen
    self.window.update(*update_input["args"], **update_input["kwargs"])
RuntimeError: maximum recursion depth exceeded in cmp
# [... then the previous 4 lines are repeated ~50 times by eyeball]
# [... then the first 4 lines are repeated again...]
```

**Comment by oliver-sanders** [comment]
Closing as the splash screen was removed with the GTK GUI.
