### ISSUE TITLE
rosie go: libsecret authentication caching issue

### ISSUE THREAD

**Issue by matthewrmshin** [metomi/rose#2245]
Rosie Go is currently unable to use libsecret. Inserting a `traceback.print_exc` in the exception handler of `ImportError` gives us this traceback:

```
Traceback (most recent call last):
  File "/home/matt/rose.git/lib/python/rosie/ws_client_auth.py", line 39, in <module>
    from gi import require_version, pygtkcompat
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 33, in <module>
    raise ImportError('When using gi.repository you must not import static '
ImportError: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".
```

However, even after converting all instants of `import gobject` to `from gi.repository import GObject` in our source tree, it still gives us the same error.

**Comment by wxtim** [comment]
Changing 
```python
from gi.repository import GObject
import gtk
# to
import gtk
from gi.repository import GObject
```
produces an entirely different error:
```
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/local/tpilling/rose/lib/python/rosie/browser/main.py", line 62, in <module>
    import rosie.browser.util
  File "/home/local/tpilling/rose/lib/python/rosie/browser/util.py", line 32, in <module>
    from rosie.ws_client import RosieWSClientError
  File "/home/local/tpilling/rose/lib/python/rosie/ws_client.py", line 35, in <module>
    from rosie.ws_client_auth import RosieWSClientAuthManager
  File "/home/local/tpilling/rose/lib/python/rosie/ws_client_auth.py", line 42, in <module>
    from gi.repository import Secret
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 145, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/Gio.py", line 49, in <module>
    FileEnumerator = override(FileEnumerator)
  File "/usr/lib64/python2.7/site-packages/gi/overrides/__init__.py", line 198, in override
    'introspection typelib' % type_.__name__)
TypeError: Can not override a type FileEnumerator, which is not in a gobject introspection typelib
```
This appears to have fixed the original error, but line 42 has a second error in it.

**Comment by wxtim** [comment]
[Pull Request](https://github.com/metomi/rose/pull/2254) - I'm not  altogether happy with this PR: Although it appears to fix the problem I'm not completely sure why.
