### ISSUE TITLE
Rose SVN Wrapper Picks up Local Python in tests

### ISSUE THREAD

**Issue by wxtim** [metomi/rose#2337]
The following tests
```
Test Summary Report
-------------------
./t/rosa-svn-pre-commit/03-meta.t                                (Wstat: 0 Tests: 10 Failed: 7)
  Failed tests:  2-4, 6, 8-10
./t/rosa-svn-post-commit/02-mail-owner-passwd.t                  (Wstat: 0 Tests: 30 Failed: 25)
  Failed tests:  5-9, 11-30
./t/rosa-svn-post-commit/03-unicode.t                            (Wstat: 0 Tests: 10 Failed: 8)
  Failed tests:  2-5, 7-10
./t/rosa-svn-post-commit/00-basic.t                              (Wstat: 0 Tests: 71 Failed: 57)
  Failed tests:  2-6, 8-12, 14-18, 20-24, 26-30, 32-34, 36-37
                39-44, 46-50, 52-56, 58-62, 64-66, 68, 70-71
./t/rosa-db-create/00-basic.t                                    (Wstat: 0 Tests: 16 Failed: 3)
  Failed tests:  8, 12, 16
./t/rosa-svn-pre-commit/00-basic.t                               (Wstat: 256 Tests: 99 Failed: 53)
  Failed tests:  3, 6, 9, 12, 15, 18-19, 21-23, 25-26, 29-30
                32-34, 36-38, 40-42, 44-45, 48, 51, 54
                57-58, 60-61, 64-65, 67-68, 71-72, 74-75
                78-79, 81-82, 85-86, 88-89, 92, 95-96, 98-99
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 117 tests but ran 99.
./t/rosa-svn-post-commit/01-mail-passwd.t                        (Wstat: 0 Tests: 30 Failed: 29)
  Failed tests:  1-9, 11-30
./t/docs/02-tutorial-suites.t                                    (Wstat: 0 Tests: 30 Failed: 1)
  Failed test:  7
  Parse errors: Bad plan.  You planned 33 tests but ran 30.
./t/rosa-svn-pre-commit/02-passwd.t                              (Wstat: 0 Tests: 13 Failed: 7)
  Failed tests:  2, 4-5, 7, 9, 11, 13
./t/rosa-svn-pre-commit/01-rosie-create.t                        (Wstat: 0 Tests: 18 Failed: 17)
  Failed tests:  1-15, 17-18
```
fail because rosa picks up local python3 versions causing failure when modules not in that environment fail.
Example failure - note the `/usr/lib/python3.4/runpy.py` and failure to load jinja2
```python
+[FAIL] svn import -q -m foo-aa000:\ new\ suite /var/tmp/tmp_4rsua7u file:///var/tmp/tmp.Cok7WOnwGw/repos/foo/a/a/0/0/0/trunk # return-code=1, stderr=
+[FAIL] svn: E165001: Commit blocked by pre-commit hook (exit code 1) with output:
+[FAIL] Traceback (most recent call last):
+[FAIL]   File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
+[FAIL]     "__main__", mod_spec)
+[FAIL]   File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
+[FAIL]     exec(code, run_globals)
+[FAIL]   File "$PLACE/rose.git/lib/python/rosie/svn_pre_commit.py", line 34, in <module>
+[FAIL]     from rose.macros import DefaultValidators
+[FAIL]   File "$PLACE/rose.git/lib/python/rose/macros/__init__.py", line 28, in <module>
+[FAIL]     from . import rule
+[FAIL]   File "$PLACE/rose.git/lib/python/rose/macros/rule.py", line 24, in <module>
+[FAIL]     import jinja2
+[FAIL] ImportError: No module named 'jinja2'
+[FAIL] 
```
contrast my desktop 
```bash
>  python3 -c "import sys; print(sys.version); import jinja2 "
3.4.9 (Obscured) 
[More than I want to tell you about my system]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'jinja2'
```
with my conda env
```
python3 -c "import sys; print(sys.version); import jinja2 "
3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0]
```

**Comment by sadielbartholomew** [comment]
As discussed with @wxtim offline, this *should* simply be a local set-up issue relating to not pointing to the correct ``PATH`` via a ``lib/bash/rose_site_init`` file, so I strongly suspect we can close this Issue under the 'Invalid' flag. Details on how to set-up that file sent, now awaiting confirmation that tests that pass as per Travis CI & my local environment.

**Comment by wxtim** [comment]
fixed

`export PATH=/home/h02/tpilling/miniconda3/envs/python_tree_heaven/bin:$PATH`
