### ISSUE TITLE
rosie: investigate password caching

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2661]
Investigate password caching e.g. with GPG agent w/ Rose 2 deployed via Conda environments.

Rosie uses password caching to allow it to interact with SVN repositories without users having to type their passwords every time they do so. Try out the latest version of Rosie with caching systems like gpg-agent to make sure it still works and add CI testing where possible.

**Comment by hjoliver** [comment]
I'm not entirely sure if this is the right issue, but attempting to symlink `rosie` to the new `cylc` wrapper at my site results in this problem:

```console
$ rosie version --long
rosie 2.0.2 (/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1)

$ rosie hello
Traceback (most recent call last):
  File "/opt/nesi/share/cylc/8.1.1/bin/rosie", line 10, in <module>
    sys.exit(rosie())
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rose/rose.py", line 243, in rosie
    main(
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rose/rose.py", line 347, in main
    exec_sub_cmd(ns, sub_cmd, cmd_args)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rose/rose.py", line 146, in exec_sub_cmd
    _exec_python(
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rose/rose.py", line 182, in _exec_python
    fcn()
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client_cli.py", line 52, in _inner
    sys.exit(fcn())
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client_cli.py", line 131, in hello
    ws_client = RosieWSClient(prefixes=opts.prefixes, event_handler=report)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client.py", line 116, in __init__
    self.set_prefixes(prefixes)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client.py", line 137, in set_prefixes
    ok_prefixes = self.hello(return_ok_prefixes=True)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client.py", line 331, in hello
    return self._get("hello", return_ok_prefixes=return_ok_prefixes)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client.py", line 177, in _get
    request_details[full_url] = self._create_request_detail(
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client.py", line 294, in _create_request_detail
    requests_kwargs["auth"] = auth_manager.get_auth()
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client_auth.py", line 407, in get_auth
    self._prompt(is_retry)
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rosie/ws_client_auth.py", line 480, in _prompt
    icon_path = ResourceLocator.default().locate("images/rosie-icon.png")
  File "/scale_wlg_persistent/filesets/opt_nesi/share/cylc/8.1.1/lib/python3.9/site-packages/metomi/rose/resource.py", line 171, in locate
    raise ResourceError(key)
metomi.rose.resource.ResourceError: images/rosie-icon.png: resource not found.
```

For the moment, reverting to using `rosie` via Rose-2019

**Comment by dpmatthews** [comment]
@hjoliver The latest wrapper script should call Rose 2019.01: https://github.com/cylc/cylc-flow/pull/4837

**Comment by hjoliver** [comment]
Roger that. We achieved the same thing here by symlinking `rosie` to the old `rose`-specific wrapper. However, I guess `rose edit` will need the new wrapper.
