### ISSUE TITLE
rose date: 

### ISSUE THREAD

**Issue by oliver-sanders** [metomi/rose#2665]
`rose date` fails when run from workflows that use integer cycling:

```
$ ROSE_CYCLING_MODE=integer rose date    
WARNING: "rose date" is deprecated, use the "isodatetime" command.    
Traceback (most recent call last):    
  File "~/mambaforge/envs/cylc.dev/bin/rose", line 8, in <module>                     
    sys.exit(rose())    
  File "~/mambaforge/envs/cylc.dev/lib/python3.7/site-packages/metomi/rose/rose.py", line 235, in rose                     
    f'Rose {__version__}:'    
  File "~/mambaforge/envs/cylc.dev/lib/python3.7/site-packages/metomi/rose/rose.py", line 347, in main                     
    exec_sub_cmd(ns, sub_cmd, cmd_args)    
  File "~/mambaforge/envs/cylc.dev/lib/python3.7/site-packages/metomi/rose/rose.py", line 150, in exec_sub_cmd 
    args,    
  File "~/mambaforge/envs/cylc.dev/lib/python3.7/site-packages/metomi/rose/rose.py", line 182, in _exec_python 
    fcn()    
  File "~/mambaforge/envs/cylc.dev/lib/python3.7/site-packages/metomi/rose/date_cli.py", line 275, in main                     
    sys.exit(iso_main())    
  File "~/isodatetime/metomi/isodatetime/main.py", line 317, in main                         
    ref_point_str=args.ref_point_str)    
  File "~/isodatetime/metomi/isodatetime/datetimeoper.py", line 92, in __init__                         
    self.set_calendar_mode(calendar_mode)    
  File "~/isodatetime/metomi/isodatetime/datetimeoper.py", line 231, in set_calendar_mode                         
    Calendar.default().set_mode(calendar_mode)    
  File "~/isodatetime/metomi/isodatetime/data.py", line 98, in set_mode                                                            
    days_in_months, days_in_months_leap = self.MODES[mode.lower()]    
KeyError: 'integer'    
```

**Comment by oliver-sanders** [comment]
Closed by #2666
